version: '3'

services:
  db:
    image: mariadb:latest  # Use the MariaDB image
    platform: linux/x86_64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: example_user_password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    platform: linux/x86_64
    ports:
      - "8000:80"
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: example_user_password
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data:
  wordpress_data:
